#! /usr/bin/python

import sys
import argparse

from port_scanner.scanner import PortScanner
from port_scanner.values import *


def exit_failure(message):
    sys.stderr.write(message)
    sys.stderr.flush()
    sys.exit(1)


def syntax_error_msg(section):
    return '%s uses invalid syntax for port list.\n' % section


def port_list_from_string(port_string):
    """Convert a comma- and hyphen-separated string of integers
    to a list of unique integers. Exit on syntax errors.
    """
    port_list = []
    comma_separated = port_string.split(',')
    for section in comma_separated:
        if '-' not in section:
            try:
                port_num = int(section)
                port_list.append(port_num)
            except ValueError:
                exit_failure(syntax_error_msg(section))
        else:
            lower_and_upper = section.split('-')
            try:
                lower = int(lower_and_upper[0])
                upper = int(lower_and_upper[1])
            except (IndexError, ValueError):
                exit_failure(syntax_error_msg(section))

            if lower > upper:
                exit_failure('Section %s is an invalid range.\n' % section)

            port_list.extend(range(lower, upper + 1))

    return list(set(port_list))


def handle_args():
    """Parse command line argruments.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('host', metavar='HOST',
                        help='The hostname or IP address to port scan. ' +
                             'If a hostname is given which resolves to multiple addresses, ' +
                             'only one address will be scanned.')
    parser.add_argument('--ports', '-p',
                        default='1-65535',
                        help='The hyphen- and/or comma-separated port list to scan.\n' +
                             'e.g. \'1,2-8,9,10-20\'\n' +
                             'Defaults to ports 1-65535.\n' +
                             'Ports outside this range will be ignored.')
    parser.add_argument('--show-closed', '-c',
                        dest='show_closed', action='store_true',
                        help='If present, closed ports are displayed.')

    args = parser.parse_args()
    return args


def print_results(host, results_map, show_closed=False):
    """Print scan results to stdout.""
    Args:
        host(str): The host that was scanned.
        results_map(dict): Dictionary of (port, result) mappings
            as found in a port_scanner.scanner.PortScanner object after a scan.

    Keyword Args:
        show_closed(bool): Whether to show the closed ports.
    """
    class ResultWorker(object):
        def __init__(self, word, count):
            self.word = word
            self.count = count

    result_dict = {
        RESULT_OPEN: ResultWorker('open', 0),
        RESULT_FILTERED: ResultWorker('filtered', 0),
        RESULT_CLOSED: ResultWorker('closed', 0),
        RESULT_UNKNOWN: ResultWorker('unknown', 0)
    }

    dont_detail = [RESULT_FILTERED]
    if not show_closed:
        dont_detail.append(RESULT_CLOSED)

    results_str_list = []
    for port in results_map:
        result = results_map[port]
        result_dict[result].count += 1
        if result not in dont_detail:
            results_str_list.append('%s\t\t%s' % (port, result_dict[result].word))

    print "RESULTS"
    print "======="
    print '%s seems to have %d open, %d closed, %d filtered, and %d unknown ports.' \
        % (host,
           result_dict[RESULT_OPEN].count,
           result_dict[RESULT_CLOSED].count,
           result_dict[RESULT_FILTERED].count,
           result_dict[RESULT_UNKNOWN].count)

    if results_str_list:
        print
        print 'PORT\t\tSTATUS'
        print '\n'.join(results_str_list)


def main():
    # parse args
    args = handle_args()
    host = args.host
    port_list = port_list_from_string(args.ports)
    show_closed = args.show_closed

    print 'Staring port scan of host %s.\n' % host

    # run scan
    ps = PortScanner(host, port_list)
    ps.run()

    # print results
    print_results(host, ps.results_map, show_closed=show_closed)

if __name__ == "__main__":
    main()
